GRANT USAGE ON *.* TO 'holmon'@'%' IDENTIFIED BY PASSWORD '*62A67A0401F947AA27EF91732DB9DF75BEC34EF0';

GRANT ALL PRIVILEGES ON `holmonflows`.* TO 'holmon'@'%' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `holmondns`.* TO 'holmon'@'%' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `holmon%`.* TO 'holmon'@'%';
