# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dns_statistics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dns_statistics.proto',
  package='',
  serialized_pb='\n\x14\x64ns_statistics.proto\"\xaa\x03\n\x0e\x64ns_statistics\x12)\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1b.dns_statistics.DataMessage\x12/\n\x07\x63ontrol\x18\x02 \x01(\x0b\x32\x1e.dns_statistics.ControlMessage\x1a\x87\x02\n\x0b\x44\x61taMessage\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x12\n\nip_address\x18\x04 \x03(\t\x12\x19\n\x11\x61_records_counter\x18\x05 \x03(\r\x12\x1e\n\x16ip_distance_moving_avg\x18\x07 \x01(\x02\x12\x1b\n\x13unique_ttls_counter\x18\x08 \x01(\x02\x12\x16\n\x0ettl_moving_avg\x18\t \x01(\x02\x12\x18\n\x10ttl_standard_dev\x18\n \x01(\x02\x12\x19\n\x11\x61_queries_counter\x18\x0f \x01(\r\x12\x1d\n\x15\x64name_queries_counter\x18\x10 \x01(\r\x12\x12\n\nas_counter\x18\x11 \x01(\r\x1a\x32\n\x0e\x43ontrolMessage\x12\x11\n\ttimestamp\x18\x01 \x02(\r\x12\r\n\x05start\x18\x02 \x02(\x08')




_DNS_STATISTICS_DATAMESSAGE = _descriptor.Descriptor(
  name='DataMessage',
  full_name='dns_statistics.DataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dns_statistics.DataMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='dns_statistics.DataMessage.ip_address', index=1,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='a_records_counter', full_name='dns_statistics.DataMessage.a_records_counter', index=2,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip_distance_moving_avg', full_name='dns_statistics.DataMessage.ip_distance_moving_avg', index=3,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unique_ttls_counter', full_name='dns_statistics.DataMessage.unique_ttls_counter', index=4,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ttl_moving_avg', full_name='dns_statistics.DataMessage.ttl_moving_avg', index=5,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ttl_standard_dev', full_name='dns_statistics.DataMessage.ttl_standard_dev', index=6,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='a_queries_counter', full_name='dns_statistics.DataMessage.a_queries_counter', index=7,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dname_queries_counter', full_name='dns_statistics.DataMessage.dname_queries_counter', index=8,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='as_counter', full_name='dns_statistics.DataMessage.as_counter', index=9,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=136,
  serialized_end=399,
)

_DNS_STATISTICS_CONTROLMESSAGE = _descriptor.Descriptor(
  name='ControlMessage',
  full_name='dns_statistics.ControlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='dns_statistics.ControlMessage.timestamp', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='dns_statistics.ControlMessage.start', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=401,
  serialized_end=451,
)

_DNS_STATISTICS = _descriptor.Descriptor(
  name='dns_statistics',
  full_name='dns_statistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='dns_statistics.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='control', full_name='dns_statistics.control', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DNS_STATISTICS_DATAMESSAGE, _DNS_STATISTICS_CONTROLMESSAGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=451,
)

_DNS_STATISTICS_DATAMESSAGE.containing_type = _DNS_STATISTICS;
_DNS_STATISTICS_CONTROLMESSAGE.containing_type = _DNS_STATISTICS;
_DNS_STATISTICS.fields_by_name['data'].message_type = _DNS_STATISTICS_DATAMESSAGE
_DNS_STATISTICS.fields_by_name['control'].message_type = _DNS_STATISTICS_CONTROLMESSAGE
DESCRIPTOR.message_types_by_name['dns_statistics'] = _DNS_STATISTICS

class dns_statistics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class DataMessage(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DNS_STATISTICS_DATAMESSAGE

    # @@protoc_insertion_point(class_scope:dns_statistics.DataMessage)

  class ControlMessage(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DNS_STATISTICS_CONTROLMESSAGE

    # @@protoc_insertion_point(class_scope:dns_statistics.ControlMessage)
  DESCRIPTOR = _DNS_STATISTICS

  # @@protoc_insertion_point(class_scope:dns_statistics)


# @@protoc_insertion_point(module_scope)
